---
# https://circleci.com/developer/orbs/orb/circleci/terraform
version: 2.1
orbs:
  terraform: circleci/terraform@3.1
workflows:
  deploy_infra:
    jobs:
    - terraform/fmt:
          checkout: true
          context: terraform
    - terraform/validate:
        checkout: true
        context: terraform
    - terraform/plan:
        checkout: true
        context: terraform
        environment:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        persist-workspace: true
        requires:
        - terraform/validate
    - terraform/apply:
        attach-workspace: true
        context: terraform
        environment:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        filters:
          branches:
            only: main
        requires:
        - terraform/plan
# workflows:
#   delete_infra:
#     jobs:
#       - terraform/destroy:
#           executor: terraform/default
#           steps:
#             - checkout
#             - run:
#                 name: Terraform Destroy
#                 command: |
#                   terraform init -backend-config="bucket=tfdemostatebucket" -backend-config="key=kishan/circleci.tfstate" -backend-config="region=ap-south-1"
#                   terraform destroy -auto-approve